# Generated by Django 5.1.6 on 2025-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('in', 'Inactive')], max_length=20),
        ),
    ]
