# Generated by Django 5.1.6 on 2025-02-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='desc',
            new_name='address',
        ),
    ]
