# Generated by Django 5.1.6 on 2025-02-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0002_remove_subject_date'),
        ('teachers', '0003_rename_desc_teacher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='teachers.status'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teacher', to='subjects.subject'),
        ),
    ]
