# Generated by Django 5.1.6 on 2025-02-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0002_remove_teacher_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=25)),
                ('schedule', models.CharField(choices=[('morning', 'Morning Session'), ('afternoon', 'Afternoon Session'), ('evening', 'Evening Session')], max_length=25)),
                ('max_students', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('subjects', models.ManyToManyField(related_name='groups', to='subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teachers.teacher')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
