# Generated by Django 5.1.6 on 2025-02-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
