# Generated by Django 5.1.6 on 2025-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_alter_department_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(blank=True, choices=[('ac', 'Active'), ('ic', 'Inactive')], max_length=2),
        ),
    ]
